apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.selector.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      name: {{ .Values.selector.app }}
      labels:
        app: {{ .Values.selector.app }}
    spec:
      containers:
      - image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: main
      imagePullSecrets:
      - name:  {{ .Values.imagePullSecret }}
